openapi: 3.0.0
info:
  description: Sandbox for testing API behavior
  title: API sandbox
  version: '0.0.1'

paths:
  /health:
    get:
      description: Healthcheck of app
      responses:
        '204':
          description: Everything is fine
        '503':
          description: App is shutting down

  /hello/${name}:
    options:
      description: Show hello options
      responses:
        '204':
          description: Headers only response

    get:
      description: Say hello
      parameters:
        - name: name
          in: path
          description: Name to greet
          required: false
          schema:
            type: string

      responses:
        '200':
          description: Greeting message
          content:
            application/json:
              schema:
                type: object
                properties:
                  greeting:
                    type: string
                    description: Greeting sentence

servers:
  - url: 'https://api.vibioh.fr/'
  - url: 'wss://api.vibioh.fr/'