openapi: 3.0.0
info:
  description: Sandbox for testing API behavior
  title: API sandbox
  version: "0.0.1"

paths:
  /health:
    get:
      description: Healthcheck of app
      responses:
        '204':
          description: Everything fine
        '503':
          description: App is shutting down

  /hello:
    get:
      description: Say hello
      responses:
        '200':
          description: Greeting message
          content:
            application/json:
              schema:
                type: object
                properties:
                  greeting:
                    type: string
                    description: Greeting words

servers:
  - url: 'https://api.vibioh.fr/'
  - url: 'wss://api.vibioh.fr/'